---
name: broker-registrar

instance_groups:
- name: broker-registrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-registrar
    release: broker-registrar
    consumes:
      servicebroker:
        deployment: ((servicebroker_deployment))
    properties:
      cf:
        api_url: ((cf_api_url))
        username: ((cf_admin_username))
        password: ((cf_admin_password))
        skip_ssl_validation: ((cf_skip_ssl_validation))

- name: broker-deregistrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-deregistrar
    release: broker-registrar

releases:
  name: broker-registrar
  version: latest
  # version: 2.0.0
  # url: https://bosh.io/d/github.com/cloudfoundry-community/broker-registrar-boshrelease?v=2.0.0
  # sha1: 83b61f06e43c27845deb59597504e55ee887897e
