---
name: broker-registrar-((servicebroker_deployment))

instance_groups:
- name: broker-registrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-registrar
    release: broker-registrar
    consumes:
      servicebroker:
        from: servicebroker
        deployment: ((servicebroker-deployment))
    properties:
      cf:
        api_url: ((cf-api-url))
        username: ((cf-admin-username))
        password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))

- name: broker-deregistrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-deregistrar
    release: broker-registrar
    consumes:
      servicebroker:
        from: servicebroker
        deployment: ((servicebroker-deployment))
    properties:
      cf:
        api_url: ((cf-api-url))
        username: ((cf-admin-username))
        password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))

releases:
- name: broker-registrar
  version: 3.2.0
  url: https://bosh.io/d/github.com/cloudfoundry-community/broker-registrar-boshrelease?v=3.2.0
  sha1: c3c816470e32d6957fcda1b19c1647ff9acba8e2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false
