---
name: broker-registrar-((servicebroker_deployment))

instance_groups:
- name: broker-registrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: minimal
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-registrar
    release: broker-registrar
    properties:
      servicebroker:
        url: https://my-broker.system.domain
        name: mybroker
        username: broker
        password: broker
      cf:
        api_url: ((cf-api-url))
        username: ((cf-admin-username))
        password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))

- name: broker-deregistrar
  instances: 1
  azs: [z1]
  lifecycle: errand
  vm_type: minimal
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: broker-deregistrar
    release: broker-registrar
    properties:
      servicebroker:
        name: mybroker
      cf:
        api_url: ((cf-api-url))
        username: ((cf-admin-username))
        password: ((cf-admin-password))
        skip_ssl_validation: ((cf-skip-ssl-validation))

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: broker-registrar
  sha1: 14efb839e31d6d9daa023a20b3ce4de4dc953b8a
  stemcell:
    os: ubuntu-xenial
    version: "250.38"
  url: https://s3.amazonaws.com/broker-registrar-boshrelease/compiled-releases/broker-registrar/broker-registrar-3.4.0-ubuntu-xenial-250.38-20190510-010623-186187767-20190510010623.tgz
  version: 3.4.0
