---
meta:
  name:    broker-registrar
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  test-errand: ~

  initial_version: 3.3.0

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  bosh-lite:
    target:   ((bosh-lite-environment))
    cacert:   ((bosh-lite-ca-cert))
    username: ((bosh-lite-client))
    password: ((bosh-lite-client-secret))
    cf:
      deployment_name: (( vault "secret/bosh-lites/lite49/cf:deployment_name" ))
      api_url:         (( vault "secret/bosh-lites/lite49/cf:api_url" ))
      admin_username:  admin
      admin_password:  (( vault "secret/bosh-lites/lite49/cf:admin_password" ))
      system_domain:   (( vault "secret/bosh-lites/lite49/cf:system_domain" ))
      servicebroker_deployment: testflight-docker-broker

  manifest:
    vars: (( concat
      "\ncf-api-url=" meta.bosh-lite.cf.api_url
      "\ncf-admin-username=" meta.bosh-lite.cf.admin_username
      "\ncf-admin-password=" meta.bosh-lite.cf.admin_password
      "\ncf-skip-ssl-validation=true"
      "\nservicebroker-deployment=" meta.bosh-lite.cf.servicebroker_deployment ))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  cloudfoundry-community
    repo:   (( grab meta.pipeline ))
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       (( concat meta.name "-boshrelease" ))
    blob_success:  '(( concat ": New version of  was detected, and updated in master. <" meta.url "/teams//pipelines/| Cut a new release?>" ))'
    blob_failure:  '(( concat ": :airplane_arriving: <" meta.url "/teams//pipelines//jobs//builds/| Failed to update the blob for >" ))'
